image: gitpod/workspace-full:latest

tasks:
  - name: Run python flask webserver
    command: python3 app.py

ports:
  - port: 8000
    onOpen: open-preview
    name: Website
    description: Website Preview
    visibility: private
    protocol: http

vscode:
  extensions:
    - ecmel.vscode-html-css
    - Gydunhn.javascript-essentials
    - ms-python.python
    - jnoortheen.nix-ide
    - castrogusttavo.min-theme
    - castrogusttavo.symbols
    - antfu.icons-carbon
    - gruntfuggly.todo-tree
    - mhutchie.git-graph
    - donjayamanne.githistory
    - timonwong.shellcheck
    - foxundermoon.shell-format
    - tyriar.sort-lines
    - yzhang.markdown-all-in-one
    - davidanson.vscode-markdownlint
    - naumovs.color-highlight
    - oderwat.indent-rainbow
    - tamasfe.even-better-toml
    - idleberg.icon-fonts
    - anseki.vscode-color
    - aaron-bond.better-comments
    - ibm.output-colorizer
    - chouzz.vscode-better-align
    - esbenp.prettier-vscode
